# Scheme name: Jellybeans Dark
# Scheme author: https://github.com/catppuccin/catppuccin
# Template author: Tinted Theming (https://github.com/tinted-theming)

"attributes" = "base09"
"comment" = { fg = "base03", modifiers = ["italic"] }
"constant" = "base09"
"constant.character.escape" = "base0C"
"constant.numeric" = "base09"
"constructor" = "base0D"
"debug" = "base03"
"diagnostic" = { modifiers = ["underlined"] }
"diff.delta" = "base09"
"diff.minus" = "base08"
"diff.plus" = "base0B"
"error" = "base08"
"function" = "base0D"
"hint" = "base03"
"info" = "base0D"
"keyword" = "base0E"
"label" = "base0E"
"namespace" = "base0E"
"operator" = "base05"
"special" = "base0D"
"string"  = "base0B"
"type" = "base0A"
"variable" = "base08"
"variable.other.member" = "base0B"
"warning" = "base09"

"markup.bold" = { fg = "base0A", modifiers = ["bold"] }
"markup.heading" = "base0D"
"markup.italic" = { fg = "base0E", modifiers = ["italic"] }
"markup.link.text" = "base08"
"markup.link.url" = { fg = "base09", modifiers = ["underlined"] }
"markup.list" = "base08"
"markup.quote" = "base0C"
"markup.raw" = "base0B"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diagnostic.error" = { underline = { style = "curl" } }

"ui.background" = { bg = "base00" }
"ui.bufferline.active" = { fg = "base00", bg = "base03", modifiers = ["bold"] }
"ui.bufferline" = { fg = "base04", bg = "base00" }
"ui.cursor" = { fg = "base0A", modifiers = ["reversed"] }
"ui.cursor.insert" = { fg = "base0A", modifiers = ["reversed"] }
"ui.cursorline.primary" = { fg = "base05", bg = "base01" }
"ui.cursor.match" = { fg = "base0A", modifiers = ["reversed"] }
"ui.cursor.select" = { fg = "base0A", modifiers = ["reversed"] }
"ui.gutter" = { bg = "base00" }
"ui.help" = { fg = "base06", bg = "base01" }
"ui.linenr" = { fg = "base03", bg = "base00" }
"ui.linenr.selected" = { fg = "base04", bg = "base01", modifiers = ["bold"] }
"ui.menu" = { fg = "base05", bg = "base01" }
"ui.menu.scroll" = { fg = "base03", bg = "base01" }
"ui.menu.selected" = { fg = "base01", bg = "base04" }
"ui.popup" = { bg = "base01" }
"ui.selection" = { bg = "base02" }
"ui.selection.primary" = { bg = "base02" }
"ui.statusline" = { fg = "base04", bg = "base01" }
"ui.statusline.inactive" = { bg = "base01", fg = "base03" }
"ui.statusline.insert" = { fg = "base00", bg = "base0B" }
"ui.statusline.normal" = { fg = "base00", bg = "base03" }
"ui.statusline.select" = { fg = "base00", bg = "base0F" }
"ui.text" = "base05"
"ui.text.focus" = "base05"
"ui.virtual.indent-guide" = { fg = "base03" }
"ui.virtual.inlay-hint" = { fg = "base03" }
"ui.virtual.ruler" = { bg = "base01" }
"ui.virtual.jump-label" = { fg = "base0A", modifiers = ["bold"] }
"ui.window" = { bg = "base01" }

[palette]
0base00 = "#151515" # Default Background
0base01 = "#181818" # Lighter Background (Used for status bars, line number and folding marks)
0base02 = "#313131" # Selection Background
0base03 = "#454545" # Comments, Invisibles, Line Highlighting
0base04 = "#888888" # Dark Foreground (Used for status bars)
0base05 = "#e8e8d3" # Default Foreground, Caret, Delimiters, Operators
0base06 = "#b0d0f0" # Light Foreground (Not often used)
0base07 = "#b4befe" # Light Background (Not often used)
0base08 = "#cf6a4c" # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
0base09 = "#fab387" # Integers, Boolean, Constants, XML Attributes, Markup Link Url
0base0A = "#fad07a" # Classes, Markup Bold, Search Text Background
0base0B = "#99ad6a" # Strings, Inherited Class, Markup Code, Diff Inserted
0base0C = "#668799" # Support, Regular Expressions, Escape Characters, Markup Quotes
0base0D = "#8197bf" # Functions, Methods, Attribute IDs, Headings
0base0E = "#cba6f7" # Keywords, Storage, Selector, Markup Italic, Diff Changed
0base0F = "#f2cdcd" # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>

base00 = "#151515"
base01 = "#202020"
base02 = "#303030"
base03 = "#505050"
base04 = "#b0b0b0"
base05 = "#d0d0d0"
base06 = "#e0e0e0"
base07 = "#f5f5f5"
base08 = "#cf6a4c"
base09 = "#eda987"
base0A = "#d8ad4c"
base0B = "#99ad6a"
base0C = "#71b9f8"
base0D = "#597bc5"
base0E = "#a037b0"
base0F = "#deaf8f"
