# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# This file should contain a [[items]] section for each application you want themed
# You can also set a shell (outside items) on which to run hooks
# Check flavours repository for more information and examples


# Explanation and default values for keys:

# # Through which shell command hooks will run. The command will be replaced in '{}'
# shell = "sh -c '{}'"
#
# [[items]]
# # File to inject to, supports tilde and env var expansion. required
# file = "~/.config/example"
# # Template to use. required
# template = "example"
#
# # Subtemplate to use
# subtemplate = "default"
# # If not rewriting, on which line (usually a comment) to start replacing
# start = "# Start flavours"
# # If not rewriting, on which line (usually a comment) to stop replacing
# end = "# End flavours"
# # Should we rewrite the entire file, instead of using the above delimiters?
# rewrite = false
# # Command to execute after injecting (goes through shell)
# hook = ""
# # Whether this hook should be executed when flavours is ran with lightweight flag
# light = true
#

[[items]]
file = "~/.config/mako/config"
template = "mako"
rewrite = false
start = "# start colors"
end = "# end colors"
hook = "~/.local/bin/bde rl mako"

[[items]]
file = "~/.config/walker/themes/base16.css"
template = "walker"
rewrite = false
start = "/* start flavours */"
end = "/* end flavours */"
hook = "~/.local/bin/bde rl walker"

[[items]]
file = "~/.config/walker/themes/base16_start.css"
template = "walker"
rewrite = false
start = "/* start flavours */"
end = "/* end flavours */"
hook = "~/.local/bin/bde rl walker"

[[items]]
file = "~/.config/walker/themes/base16_wall.css"
template = "walker"
rewrite = false
start = "/* start flavours */"
end = "/* end flavours */"
hook = "~/.local/bin/bde rl walker"


[[items]]
file = "~/.config/vesktop/settings/quickCss.css"
template = "vesktop"
rewrite = true

[[items]]
file = "~/.config/hypr/conf/custom/base16.conf"
template = "hyprland"
rewrite = true

[[items]]
file = "~/.config/waybar/base16.css"
template = "waybar"
rewrite = true
hook = "~/.local/bin/bde rl waybar"

[[items]]
file = "~/.config/foot/foot.ini"
template = "foot"
rewrite = true

[[items]]
file = "~/.config/fish/themes/base16.theme"
template = "fish"
rewrite = true

[[items]]
file = "~/.config/ghostty/themes/base.conf"
template = "ghostty"
rewrite = true
hook = "~/.local/bin/bde rl ghostty"

[[items]]
file = "~/.config/helix/themes/base16.toml"
template = "helix"
rewrite = true
