use_nerdfont = true
flip_status_indicators = true
notify = true
library_tabs = ["tracks", "artists", "browse"]
hide_display_names = false
statusbar_format = "%title - %artists"

[track_format]
left = "%title - %artists"
center = "%album"
right = "%saved %duration"

[keybindings]
"Space"="playpause"

[theme]
background = "#191724"
primary = "#e0def4"
secondary = "#6e6a86"
title = "#c4a7e7"
playing = "#c4a7e7"
playing_selected = "#524f67"
playing_bg = "#191724"
highlight = "#e0def4"
highlight_bg = "#1f1d2e"
error = "#1f1d2e"
error_bg = "#eb6f92"
statusbar = "#c4a7e7"
statusbar_progress = "#c4a7e7"
statusbar_bg = "#191724"
cmdline = "#e0def4"
cmdline_bg = "#191724"
search_match = "#c4a7e7"