[general]
import = [
    "~/.config/alacritty/themes/themes/colors.toml"
]

[window]
dimensions = { columns = 125, lines = 28 }
opacity = 0.75
blur = true

[font]
normal = { family = "JetBrains Mono", style = "Semibold" }
size = 12.0

[cursor]
smooth_motion = true
smooth_motion_factor = 1.0
smooth_motion_spring = 0.5
smooth_motion_max_stretch_x = 3.0
smooth_motion_max_stretch_y = 3.0
block_replace_shape = "beam"

[keyboard]
bindings = [
  { key = "Q", mods = "Control", action = "Quit" },
  { key = "T", mods = "Control", action = "SpawnNewInstance" }
]
