general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 13

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Regular"

[window]
padding = { x = 20, y = 10 }
title = "Terminal"
dynamic_padding = true
